import { AppProvider } from '../context/AppContext'
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata= {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <link rel='manifest' href='/manifest.json' />
        <link rel='apple-touch-icon' href='/favicon.png' />
        <meta name="theme-color" content="black" />
        <meta name="msapplication-navbutton-color" content="black" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="description" content="Sistema Fast Cash" />
        <meta name="keywords" content="" />
        <meta name="author" content="Fast Cash" />
        <title>Fast Cash</title>
      </head>
      <AppProvider>
        <body className={inter.className}>

        <Suspense fallback={<div>Loading...</div>}>

          {children}
          </Suspense>

        </body>
      </AppProvider>
    </html>
  );
}
